# Generated by Django 4.1 on 2022-10-06 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название аллергии"),
                ),
            ],
            options={
                "verbose_name": "Аллергия",
                "verbose_name_plural": "Аллергии",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название подписки"),
                ),
                ("duration", models.IntegerField(verbose_name="Длительность в днях")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип подписки",
                "verbose_name_plural": "Типы подписки",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_meals",
                    models.SmallIntegerField(
                        verbose_name="Количество приёмов пищи в день"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        db_index=True, verbose_name="Действительно до"
                    ),
                ),
                (
                    "allergies",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="subscriptions",
                        to="web.allergy",
                        verbose_name="Аллергии",
                    ),
                ),
                (
                    "subs_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="web.subscriptiontype",
                        verbose_name="Тип подписки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Чья подписка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
