# Generated by Django 4.1 on 2022-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_subscription_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="allergies",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to="web.allergy",
                verbose_name="Аллергии",
            ),
        ),
    ]
