# Generated by Django 4.1 on 2022-10-07 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_subscription_allergies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontype",
            name="duration",
            field=models.IntegerField(verbose_name="Длительность в месяцах"),
        ),
        migrations.AlterField(
            model_name="subscriptiontype",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена за месяц",
            ),
        ),
    ]
