# Generated by Django 3.2 on 2022-10-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_update_subscription_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название игредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Вес')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Количество')),
                ('unit_title', models.CharField(max_length=20, verbose_name='еденица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рецепта')),
                ('steps', models.TextField(verbose_name='Шаги рецепта')),
                ('end_result', models.TextField(blank=True, verbose_name='Что получилось')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Калории')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Жиры')),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Углеводы')),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='web.IngredientQuantity', to='web.Ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='web.recipe'),
        ),
    ]
