# Generated by Django 4.1 on 2022-10-07 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_auto_20221007_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="number_of_person",
            field=models.SmallIntegerField(default=1, verbose_name="Количество персон"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость",
            ),
            preserve_default=False,
        ),
    ]
