# Generated by Django 3.2 on 2022-10-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_subscription_number_of_person_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_type',
            field=models.CharField(choices=[('CL', 'Классическое'), ('LC', 'Низкоуглеводное'), ('VG', 'Вегетерианское'), ('KT', 'Кето')], default='CL', max_length=2, verbose_name='Тип меню'),
            preserve_default=False,
        ),
    ]
