# Generated by Django 3.2 on 2022-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20221009_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images', verbose_name='Обложка'),
        ),
    ]
