# Generated by Django 3.2 on 2022-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_recipe_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='amount',
            new_name='amount_per_portion',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='weight',
            new_name='weight_per_portion',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='web.IngredientQuantity', to='web.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
