# Generated by Django 3.2 on 2022-10-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20221009_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='unit_title',
            new_name='unit_label',
        ),
    ]
