# Generated by Django 3.2 on 2022-10-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_update_subscription_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.recipe', verbose_name='Рецепт')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='web.subscription', verbose_name='Подписка')),
            ],
        ),
    ]
