# Generated by Django 3.2 on 2022-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_subscriptionrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание подписки'),
        ),
    ]
